### ISSUE TITLE
Can I limit the number of generated features?

### ISSUE THREAD

**Issue by SharjeelAbbas014** [Muhammad4hmed/Ghalat-Machine-Learning#3]
Hi,

First of all thanks for your awesome work. The issue I bump into today while using it is the usage of memory. I am using it in google colab with IEEE Fraud dataset from Kaggle and it says that about 10TB space will be used but I don't have enough memory to do so.
![Capture](https://user-images.githubusercontent.com/53342674/86433642-b7de0d80-bd14-11ea-9a80-8ec96635064c.PNG)

So I was wondering if there is a limit of features to be generated or may be you can implement features in small baches and keep the best one, because every time I try to rum my colab session get crashed.

**Comment by SharjeelAbbas014** [comment]
Got this issue resolved thanks

**Comment by Muhammad4hmed** [comment]
I'm glad that the issue is resolved :)
for those who are going to found this on google and having same issue, 
you can reduce the feateng_steps parameter and it will reduce features and computation power
`* feateng_steps
  the more step = the more features and more computational power required (default = 2)`
